# Generated by Django 4.2.3 on 2023-07-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='Recipee',
        ),
    ]
